export const ActionTypes = {
    REGISTER_REQUEST : "REGISTER_REQUEST",
    REGISTER_SUCCESS : "REGISTER_SUCCESS",
    REGISTER_FAILED : "REGISTER_FAILED",

    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILED : "LOGIN_FAILED",

    IMAGE_UPLOAD_REQUEST : "IMAGE_UPLOAD_REQUEST",
    IMAGE_UPLOAD_SUCCESS : " IMAGE_UPLOAD_SUCCESS",
    IMAGE_UPLOAD_FAILED : "IMAGE_UPLOAD_FAILED ",

    EDIT_PROFILE_REQUEST : "EDIT_PROFILE_REQUEST",
    EDIT_PROFILE_SUCCESS : "EDIT_PROFILE_SUCCESS",
    EDIT_PROFILE_FAILED : "EDIT_PROFILE_FAILED",

    ADD_ADDRESS_REQUEST : "ADD_ADDRESS_REQUEST",
    ADD_ADDRESS_SUCCESS : "ADD_ADDRESS_REQUEST",
    ADD_ADDRESS_FAILED : "ADD_ADDRESS_REQUEST",

    GET_ADDRESS_REQUEST : "GET_ADDRESS_REQUEST",
    GET_ADDRESS_SUCCESS : "GET_ADDRESS_REQUEST",
    GET_ADDRESS_FAILED : "GET_ADDRESS_REQUEST",

    DELETE_ADDRESS_REQUEST : " DELETE_ADDRESS_REQUEST",
    DELETE_ADDRESS_SUCCESS : " DELETE_ADDRESS_REQUEST",
    DELETE_ADDRESS_FAILED : " DELETE_ADDRESS_REQUEST",
}